/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Funky (https://sketchfab.com/vojka93)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-taxi-cab-checker-marathon-4f4c77ca12c343298e4fe42882dfc94c
title: Low Poly Taxi Cab Checker Marathon
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, OrbitControls } from "@react-three/fiber";
export function Model(props) {
  const [xRotation, setXRotation] = useState(0);
  const myMesh = React.useRef();
  const { nodes, materials } = useGLTF(
    "/low_poly_taxi_cab_checker_marathon.glb"
  );
  document.addEventListener("mousemove", (e) => {
    setXRotation(e.pageX / window.innerWidth);
  });
  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.z = 0;
    myMesh.current.rotation.y = 0.1 + Math.PI;
    myMesh.current.rotation.x = Math.PI / 2 + 0.4;
  });
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          ref={myMesh}
          rotation={[-Math.PI / 1, 0, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="BLWheel_0"
                position={[0.5, 0.05, -0.44]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="BRWheel_1"
                position={[-0.5, 0.05, -0.44]}
                rotation={[0, 0, Math.PI / 2]}
              >
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="FLWheel_2"
                position={[0.5, 0.05, 0.82]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="FRWheel_3"
                position={[-0.5, 0.05, 0.82]}
                rotation={[0, 0, Math.PI / 2]}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Taxi_6" position={[0, 0, -0.26]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.Material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/low_poly_taxi_cab_checker_marathon.glb");
